// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozckjosasowyorthaxus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96Y2tqb3Nhc293eW9ydGhheHVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNTE2MDAsImV4cCI6MjA3MTcyNzYwMH0.I7pHIMr7iTBFRrc6mllNOPk0vPXVeZWYEm433T9TnRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});